name    'superruzafa-webdev'
version '0.1.0'
source 'https://github.com/superruzafa/superruzafa-webdev'
author 'superruzafa'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'My puppet manifests for fast web development provisioning'
project_page 'UNKNOWN'
dependency 'puppetlabs/stdlib', '>= 4.4.0'
